"""sync lead model columns

Revision ID: 6d21da318163
Revises: d2faae14aa17
Create Date: 2025-09-12 19:38:19.102273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d21da318163'
down_revision: Union[str, Sequence[str], None] = 'd2faae14aa17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('job_title', sa.String(), nullable=True))
    op.add_column('leads', sa.Column('user_id', sa.UUID(), nullable=False))
    op.alter_column('leads', 'area_of_expertise_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_foreign_key(None, 'leads', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.alter_column('leads', 'area_of_expertise_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('leads', 'user_id')
    op.drop_column('leads', 'job_title')
    # ### end Alembic commands ###
