"""add lead columns from layout

Revision ID: d2faae14aa17
Revises: a1b2c3d4e5f6
Create Date: 2025-09-10 20:29:32.615734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2faae14aa17'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Todas as colunas já foram criadas na migração inicial
    # op.add_column('leads', sa.Column('cnpj', sa.String(), nullable=True))
    # op.add_column('leads', sa.Column('razao_social', sa.String(), nullable=True))
    # op.add_column('leads', sa.Column('porte_codigo', sa.String(), nullable=True))
    # op.add_column('leads', sa.Column('porte', sa.String(), nullable=True))
    # op.add_column('leads', sa.Column('capital_social', sa.String(), nullable=True))
    # op.add_column('leads', sa.Column('natureza_juridica_codigo', sa.String(), nullable=True))
    # op.add_column('leads', sa.Column('natureza_juridica', sa.String(), nullable=True))
    # op.add_column('leads', sa.Column('ente_federativo_responsavel', sa.String(), nullable=True))
    # op.add_column('leads', sa.Column('tipo', sa.String(), nullable=True))
    # op.add_column('leads', sa.Column('data_abertura', sa.Date(), nullable=True))
    # op.add_column('leads', sa.Column('nome_fantasia', sa.String(), nullable=True))
    # op.add_column('leads', sa.Column('situacao_cadastral_codigo', sa.String(), nullable=True))
    # op.add_column('leads', sa.Column('situacao_cadastral', sa.String(), nullable=True))
    # op.add_column('leads', sa.Column('situacao_cadastral_data', sa.Date(), nullable=True))
    # op.add_column('leads', sa.Column('situacao_motivo_codigo', sa.String(), nullable=True))
    # op.add_column('leads', sa.Column('situacao_motivo', sa.String(), nullable=True))
    # op.add_column('leads', sa.Column('situacao_especial_codigo', sa.String(), nullable=True))
    # op.add_column('leads', sa.Column('situacao_especial', sa.String(), nullable=True))
    # op.add_column('leads', sa.Column('situacao_especial_data', sa.Date(), nullable=True))
    # op.add_column('leads', sa.Column('telefone_principal', sa.String(), nullable=True))
    # op.add_column('leads', sa.Column('telefone_secundario', sa.String(), nullable=True))
    # op.add_column('leads', sa.Column('municipio_ibge', sa.String(), nullable=True))
    # op.add_column('leads', sa.Column('logradouro', sa.String(), nullable=True))
    # op.add_column('leads', sa.Column('numero', sa.String(), nullable=True))
    # op.add_column('leads', sa.Column('complemento', sa.String(), nullable=True))
    # op.add_column('leads', sa.Column('bairro', sa.String(), nullable=True))
    # op.add_column('leads', sa.Column('cidade', sa.String(), nullable=True))
    # op.add_column('leads', sa.Column('estado', sa.String(), nullable=True))
    # op.add_column('leads', sa.Column('cep', sa.String(), nullable=True))
    # op.add_column('leads', sa.Column('pais_codigo', sa.String(), nullable=True))
    # op.add_column('leads', sa.Column('pais', sa.String(), nullable=True))
    # op.add_column('leads', sa.Column('atividade_principal_codigo', sa.String(), nullable=True))
    # op.add_column('leads', sa.Column('atividade_principal', sa.String(), nullable=True))
    # op.add_column('leads', sa.Column('ultima_atualizacao', sa.Date(), nullable=True))
    op.alter_column('leads', 'full_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # O índice já foi criado na migração inicial
    # op.create_index(op.f('ix_leads_cnpj'), 'leads', ['cnpj'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leads_cnpj'), table_name='leads')
    op.alter_column('leads', 'full_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('leads', 'ultima_atualizacao')
    op.drop_column('leads', 'atividade_principal')
    op.drop_column('leads', 'atividade_principal_codigo')
    op.drop_column('leads', 'pais')
    op.drop_column('leads', 'pais_codigo')
    op.drop_column('leads', 'cep')
    op.drop_column('leads', 'estado')
    op.drop_column('leads', 'cidade')
    op.drop_column('leads', 'bairro')
    op.drop_column('leads', 'complemento')
    op.drop_column('leads', 'numero')
    op.drop_column('leads', 'logradouro')
    op.drop_column('leads', 'municipio_ibge')
    op.drop_column('leads', 'telefone_secundario')
    op.drop_column('leads', 'telefone_principal')
    op.drop_column('leads', 'situacao_especial_data')
    op.drop_column('leads', 'situacao_especial')
    op.drop_column('leads', 'situacao_especial_codigo')
    op.drop_column('leads', 'situacao_motivo')
    op.drop_column('leads', 'situacao_motivo_codigo')
    op.drop_column('leads', 'situacao_cadastral_data')
    op.drop_column('leads', 'situacao_cadastral')
    op.drop_column('leads', 'situacao_cadastral_codigo')
    op.drop_column('leads', 'nome_fantasia')
    op.drop_column('leads', 'data_abertura')
    op.drop_column('leads', 'tipo')
    op.drop_column('leads', 'ente_federativo_responsavel')
    op.drop_column('leads', 'natureza_juridica')
    op.drop_column('leads', 'natureza_juridica_codigo')
    op.drop_column('leads', 'capital_social')
    op.drop_column('leads', 'porte')
    op.drop_column('leads', 'porte_codigo')
    op.drop_column('leads', 'razao_social')
    op.drop_column('leads', 'cnpj')
    # ### end Alembic commands ###
